[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Exclude public client-side environment variables from Netlify's secret scanner
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_PORTAL_URL"
